### ISSUE TITLE
Error when I'm setting the min time to current time...

### ISSUE THREAD

**Issue by PemmasaniRajesh** [jjobes/SlideDateTimePicker#39]
java.lang.IllegalArgumentException: fromDate: Mon Apr 10 18:42:15 IST 2017 does not precede toDate: Mon Apr 10 13:43:15 IST 2017
                                                                      at android.widget.CalendarViewLegacyDelegate.getWeeksSinceMinDate(CalendarViewLegacyDelegate.java:926)
                                                                      at android.widget.CalendarViewLegacyDelegate.access$1400(CalendarViewLegacyDelegate.java:49)
                                                                      at android.widget.CalendarViewLegacyDelegate$WeeksAdapter.init(CalendarViewLegacyDelegate.java:1014)
                                                                      at android.widget.CalendarViewLegacyDelegate$WeeksAdapter.access$500(CalendarViewLegacyDelegate.java:992)
                                                                      at android.widget.CalendarViewLegacyDelegate.setMinDate(CalendarViewLegacyDelegate.java:507)
                                                                      at android.widget.CalendarView.setMinDate(CalendarView.java:352)
                                                                      at android.widget.DatePicker$DatePickerSpinnerDelegate.setMinDate(DatePicker.java:782)
                                                                      at android.widget.DatePicker.setMinDate(DatePicker.java:234)
                                                                      at com.github.jjobes.slidedatetimepicker.DateFragment.onCreateView(DateFragment.java:140)
                                                                      at android.support.v4.app.Fragment.performCreateView(Fragment.java:2087)
                                                                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1113)
                                                                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1295)
                                                                      at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:801)
                                                                      at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:1643)
                                                                      at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:679)
                                                                      at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:143)
                                                                      at android.support.v4.view.ViewPager.populate(ViewPager.java:1272)
                                                                      at android.support.v4.view.ViewPager.populate(ViewPager.java:1120)
                                                                      at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1646)
                                                                      at com.github.jjobes.slidedatetimepicker.CustomViewPager.onMeasure(CustomViewPager.java:70)
                                                                      at android.view.View.measure(View.java:17960)
                                                                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5698)
                                                                      at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1692)
                                                                      at android.widget.LinearLayout.measureVertical(LinearLayout.java:760)
                                                                      at android.widget.LinearLayout.onMeasure(LinearLayout.java:629)
                                                                      at android.view.View.measure(View.java:17960)
                                                                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5698)
                                                                      at android.widget.FrameLayout.onMeasure(FrameLayout.java:465)
                                                                      at android.view.View.measure(View.java:17960)
                                                                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5698)
                                                                      at android.widget.FrameLayout.onMeasure(FrameLayout.java:465)
                                                                      at android.view.View.measure(View.java:17960)
                                                                      at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5698)
                                                                      at android.widget.FrameLayout.onMeasure(FrameLayout.java:465)
                                                                      at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2798)
                                                                      at android.view.View.measure(View.java:17960)
                                                                      at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2422)
                                                                      at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1392)
                                                                      at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1648)
                                                                      at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1302)
                                                                      at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6644)
                                                                      at android.view.Choreographer$CallbackRecord.run(Choreographer.java:818)
                                                                      at android.view.Choreographer.doCallbacks(Choreographer.java:621)
                                                                      at android.view.Choreographer.doFrame(Choreographer.java:590)
                                                                      at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:804)
                                                                      at android.os.Handler.handleCallback(Handler.java:815)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                      at android.os.Looper.loop(Looper.java:194)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5763)
                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                      at java.lang.reflect.Method.invoke(Method.java:372)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by irenenaya** [comment]
What are you passing to setMaxDate()? 
The error is telling you that the date set as maxDate is smaller than the one passed to minDate, that's why the error. 
Either you're passing a smaller date to max, or you're trying to pass a larger date but you have some overflow issues (i got one of those, nothing to do with the library). If you're adding milliseconds, you may be getting an overflow.
