### ISSUE TITLE
Doesn't work on build tools 26

### ISSUE THREAD

**Issue by thomhurst** [jjobes/SlideDateTimePicker#45]
Works fine on build tools 25
Upgraded my gradle build tools to v 26.0.1

Error:

java.lang.IllegalStateException: Fragment DateFragment{22dd4c2 #0 id=0x7f08011e android:switcher:2131231006:0} declared target fragment SlideDateTimeDialogFragment{462e2d3 #0 tagSlideDateTimeDialogFragment} that does not belong to this FragmentManager!
                                                                                 at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1352)
                                                                                 at android.support.v4.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1109)
                                                                                 at android.support.v4.app.FragmentTransition.calculateFragments(FragmentTransition.java:996)
                                                                                 at android.support.v4.app.FragmentTransition.startTransitions(FragmentTransition.java:99)
                                                                                 at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2364)
                                                                                 at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2322)
                                                                                 at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2199)
                                                                                 at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:651)
                                                                                 at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:145)
                                                                                 at android.support.v4.view.ViewPager.populate(ViewPager.java:1236)
                                                                                 at android.support.v4.view.ViewPager.populate(ViewPager.java:1084)
                                                                                 at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1614)
                                                                                 at com.github.jjobes.slidedatetimepicker.CustomViewPager.onMeasure(CustomViewPager.java:70)
                                                                                 at android.view.View.measure(View.java:19734)
                                                                                 at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6120)
                                                                                 at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
                                                                                 at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
                                                                                 at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
                                                                                 at android.view.View.measure(View.java:19734)
                                                                                 at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6120)
                                                                                 at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                                 at android.view.View.measure(View.java:19734)
                                                                                 at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6120)
                                                                                 at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                                 at android.view.View.measure(View.java:19734)
                                                                                 at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6120)
                                                                                 at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
                                                                                 at com.android.internal.policy.DecorView.onMeasure(DecorView.java:687)
                                                                                 at android.view.View.measure(View.java:19734)
                                                                                 at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2271)
                                                                                 at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1331)
                                                                                 at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1607)
                                                                                 at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1246)
                                                                                 at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6301)
                                                                                 at android.view.Choreographer$CallbackRecord.run(Choreographer.java:871)
                                                                                 at android.view.Choreographer.doCallbacks(Choreographer.java:683)
                                                                                 at android.view.Choreographer.doFrame(Choreographer.java:619)
                                                                                 at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:857)
                                                                                 at android.os.Handler.handleCallback(Handler.java:751)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                 at android.os.Looper.loop(Looper.java:154)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)

**Comment by monikarora** [comment]
Hey ,also get Same Error in my app , you get any solution ?

**Comment by thomhurst** [comment]
None, I've just downgraded back to 25 for now!

**Comment by monikarora** [comment]
Okay

**Comment by csompi** [comment]
Same here!

**Comment by myproject** [comment]
Look:  https://stackoverflow.com/questions/43539929/slidedatetimepicker-datetime-picker-open-issue
And in DateFragment.java  onCreate method
 change 
               mCallback = (DateChangedListener) getTargetFragment();
  to          
               mCallback = (DateChangedListener) getParentFragment();
may be work~

**Comment by Anilugale** [comment]
java.lang.IllegalStateException: Fragment DateFragment{fb9a5e3 #0 id=0x7f0f078f android:switcher:2131691407:0} declared target fragment SlideDateTimeDialogFragment{328fbe0 #0 tagSlideDateTimeDialogFragment} that does not belong to this FragmentManager!
                                                                   at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1352)
                                                                   at android.support.v4.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1109)
                                                                   at android.support.v4.app.FragmentTransition.calculateFragments(FragmentTransition.java:996)
                                                                   at android.support.v4.app.FragmentTransition.startTransitions(FragmentTransition.java:99)
                                                                   at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2364)
                                                                   at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2322)
                                                                   at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:2199)
                                                                   at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:651)
                                                                   at android.support.v4.app.FragmentPagerAdapter.finishUpdate(FragmentPagerAdapter.java:145)
                                                                   at android.support.v4.view.ViewPager.populate(ViewPager.java:1236)
                                                                   at android.support.v4.view.ViewPager.populate(ViewPager.java:1084)
                                                                   at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1614)
                                                                   at com.ms.engage.datetimepicker.CustomViewPager.onMeasure(CustomViewPager.java:72)
                                                                   at android.view.View.measure(View.java:18788)
                                                                   at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                                   at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1465)
                                                                   at android.widget.LinearLayout.measureVertical(LinearLayout.java:748)
                                                                   at android.widget.LinearLayout.onMeasure(LinearLayout.java:630)
                                                                   at android.view.View.measure(View.java:18788)
                                                                   at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                                   at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                   at android.view.View.measure(View.java:18788)
                                                                   at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                                   at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                   at android.view.View.measure(View.java:18788)
                                                                   at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5951)
                                                                   at android.widget.FrameLayout.onMeasure(FrameLayout.java:194)
                                                                   at com.android.internal.policy.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2643)
                                                                   at android.view.View.measure(View.java:18788)
                                                                   at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2100)
                                                                   at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1191)
                                                                   at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1452)
                                                                   at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
                                                                   at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
                                                                   at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                                   at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                   at android.view.Choreographer.doFrame(Choreographer.java:606)
                                                                   at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                                   at android.os.Handler.handleCallback(Handler.java:739)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                   at android.os.Looper.loop(Looper.java:148)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)



getting same exception. on api level 26 compilation and support 26 lib. it working well in 25 and support 25

**Comment by maxid** [comment]
Follow this link to fixed it!
https://stackoverflow.com/questions/43539929/slidedatetimepicker-datetime-picker-open-issue

**Comment by pwiniars** [comment]
I've managed to fix this, along with #43. You can get it from my forked repo by adding this to gradle: compile("com.github.pwiniars:SlideDateTimePicker:v1.0.7")

**Comment by pwiniars** [comment]
I've managed to fix this issue, you can get it from my fork: compile("com.github.pwiniars:SlideDateTimePicker:v1.0.8")
